added

diff --git a/sellscript/11-13-mysql-install b/sellscript/11-13-mysql-install
--- a/sellscript/11-13-mysql-install
+++ b/sellscript/11-13-mysql-install
@@ -5,6 +5,7 @@
 # if root then proceed if not root then show the error
 # 2.Now install mysql
 # 3.check weather mysql is installed properly or not
+# $? --> to check the previous commad run properly or not
 #if installed then good other wise send error
 
 #!/bin/bash
@@ -13,8 +14,16 @@ echo "user id is $ID"
 if [ $ID -ne 0 ]
 then 
     echo "Error:: Please run this script with root user"
-    
+    exit 1 #You can give otherthan 0.
 else 
     echo "you are root user"  
 fi #if reverse indication is fi. means condition end.
 yum install mysql -y
+#$? --> it will check the previous command run successfully or not
+if [ $? -ne 0 ]
+then 
+    echo "ERROR::failed previous command"
+    exit 1
+else
+    echo "Success"
+fi
