added

diff --git a/sellscript/11-13-mysql-install b/sellscript/11-13-mysql-install
--- a/sellscript/11-13-mysql-install
+++ b/sellscript/11-13-mysql-install
@@ -18,12 +18,24 @@ then
 else 
     echo "you are root user"  
 fi #if reverse indication is fi. means condition end.
+
 yum install mysql -y
+
 #$? --> it will check the previous command run successfully or not
 if [ $? -ne 0 ]
 then 
-    echo "ERROR::failed previous command"
+    echo "ERROR::Installing mysql is failed"
     exit 1
 else
-    echo "Success"
+    echo "Installing my sql is success"
+fi
+
+yum install git -y 
+
+if [ $? -ne 0 ]
+then 
+    echo "ERROR::Installing GIT is failed"
+    exit 1
+else
+    echo "Installing GIT is success"
 fi
